Move version to libfaad/version.h file. (#129)
That makes it easier for using from different build systems.

`bootstrap` script updates `configure.ac` with version from `version.h`.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,5 +1,10 @@
 #! /bin/sh
 
+[ "a`echo c | sed s/c/b/ 2>/dev/null`" = "ab" ] || { echo >&2 "'sed' is required, but not installed."; exit 1; }
+# Determine which flag sed uses for extended regular expressions.
+# -E is POSIX. -r is for GNU sed older than 4.2.
+echo a | sed -E s/a/b/ >/dev/null 2>&1 && SED_ERE=-E || SED_ERE=-r
+
 case $OSTYPE in
 	darwin*)
 	LIBTOOLIZE=glibtoolize
@@ -8,6 +13,9 @@ case $OSTYPE in
 	LIBTOOLIZE=libtoolize
 	;;
 esac
+
+PACKAGE_VERSION=`sed -n 's/#define PACKAGE_VERSION //p' libfaad/version.h`
+sed -i.bak "$SED_ERE" "s/^(AC_INIT.+)[0-9]+\.[0-9]+\.[0-9]+(.+)$/\1$PACKAGE_VERSION\2/" configure.ac
 
 aclocal -I .                   && \
 autoheader                     && \
